/* VideoLook looks (presets). Each is a filled-in chain. evidence:
 *   'spec'  built from the specifications; no authentic surviving footage to calibrate against
 *   'research'  research-based, calibratable against reference frames but not yet calibrated
 * Sources for each stage live in the stage files; notes here say what is documented and what is judgement.
 */
"use strict";
const CRT_UK = { tube: "delta", screenIn: 22, primaries: "EBU", white: "D65" };
const LOOKS = [
  // ---------------- UK broadcast
  { id: "uk-ap-1937", group: "UK broadcast", title: "BBC Alexandra Palace, 1937", evidence: "spec",
    note: "405 lines, 5:4 picture, Emitron camera, seen on a pre-war set. No live pictures survive, so this is built from the standards; the set's size and phosphor colour are estimates.",
    s: { standard: "405-A", aspect: 1.25, camera: { type: "emitron" }, channel: { snrDb: 34 }, set: { overscan: 0.05, sharpness: 0.1 }, view: { mode: "closeup" }, display: { tube: "mono", screenIn: 12 } } },
  { id: "uk-405-1953", group: "UK broadcast", title: "405-line live studio at home, 1953", evidence: "spec",
    note: "BBC 405-line picture on a 14in set: 3 MHz, 377 lines, visible scan lines. Live pictures only survive on film, so the as-broadcast look is built from the standards.",
    s: { standard: "405-A", camera: { type: "cps_emitron" }, channel: { snrDb: 32, ghosts: [{ delayUs: 1.2, amp: 0.08, phaseDeg: 0 }] }, set: { overscan: 0.05, sharpness: 0.2 }, view: { mode: "closeup" }, display: { tube: "mono", screenIn: 14 } } },
  { id: "uk-405-telerec", group: "UK broadcast", title: "405-line telerecording, 1953", evidence: "research",
    note: "How surviving 1950s BBC television looks (e.g. The Quatermass Experiment): suppressed-field film recording keeps 188.5 lines, with spot wobble, film grain and a ~40:1 range.",
    s: { standard: "405-A", camera: { type: "emitron" }, transfer: { type: "telerecord", method: "suppressed", gauge: 35 }, enabled: { channel: false } } },
  { id: "uk-bbc2-1964", group: "UK broadcast", title: "BBC2 625-line monochrome, 1964", evidence: "research",
    note: "625 lines, 5.5 MHz, on a 19in set. The BBC2 camera fleet was not found; an image orthicon is assumed.",
    s: { standard: "625-MONO", camera: { type: "io_mono" }, channel: { snrDb: 40 }, set: { overscan: 0.04, sharpness: 0.15 }, view: { mode: "closeup" }, display: { tube: "mono", screenIn: 19, monoWhite: [0.3, 0.315] } } },
  { id: "uk-colour-studio-1975", group: "UK broadcast", title: "UK colour studio, mid-1970s", evidence: "research",
    note: "EMI 2001 four-tube Plumbicon camera, 2-inch Quad, PAL System I, on a 22in delta-gun set with the PAL delay line all British sets had.",
    s: { standard: "PAL-I", camera: { type: "emi2001" }, recording: { format: "quad_hb" }, channel: { snrDb: 42 }, decoder: { palMode: "delay" }, set: { overscan: 0.04, sharpness: 0.1 }, view: { mode: "closeup" }, display: CRT_UK } },
  { id: "uk-colour-ob-1972", group: "UK broadcast", title: "UK colour outside broadcast, early 1970s", evidence: "research",
    note: "3-tube Plumbicon OB camera on Quad. OB picture traits are not documented; the camera settings are the studio ones.",
    s: { standard: "PAL-I", camera: { type: "plumbicon3", exposure: 0.2 }, recording: { format: "quad_hb" }, channel: { snrDb: 38 }, set: { overscan: 0.04 }, view: { mode: "closeup" }, display: CRT_UK } },
  { id: "uk-drama-film-1972", group: "UK broadcast", title: "1970s drama: 16 mm film exteriors", evidence: "research",
    note: "Film shot on location, through a Rank Cintel flying-spot telecine. Run FilmLook first for the 16 mm stock, then this.",
    s: { standard: "PAL-I", transfer: { type: "telecine" }, channel: { snrDb: 42 }, set: { overscan: 0.04 }, view: { mode: "closeup" }, display: CRT_UK } },
  { id: "uk-drama-studio-1972", group: "UK broadcast", title: "1970s drama: studio video interiors", evidence: "research",
    note: "The other half of the film-and-video mix: EMI 2001 cameras on Quad, as Doctor Who's studio scenes were made.",
    s: { standard: "PAL-I", camera: { type: "emi2001" }, recording: { format: "quad_hb" }, channel: { snrDb: 42 }, set: { overscan: 0.04, sharpness: 0.1 }, view: { mode: "closeup" }, display: CRT_UK } },
  { id: "uk-colour-bw-telerec", group: "UK broadcast", title: "Colour show on B&W film (with PAL dots)", evidence: "research",
    note: "A colour programme kept only as a 16 mm black-and-white telerecording for overseas sales; the unfiltered PAL subcarrier leaves fine dots in coloured areas (the basis of BBC colour recovery). Dots show best on large documents.",
    s: { standard: "PAL-I", camera: { type: "emi2001" }, decoder: { separation: "none" }, transfer: { type: "telerecord", method: "stored", gauge: 16 }, enabled: { channel: false } } },
  { id: "uk-eng-umatic-1983", group: "UK broadcast", title: "News on U-matic, 1983", evidence: "research",
    note: "Tube ENG camera on high-band U-matic, edited and broadcast; the BBC's colour-under figures set the U-matic colour.",
    s: { standard: "PAL-I", camera: { type: "plumbicon3", overrides: { noiseDb: 36, contour: 0.55 } }, recording: { format: "umatic_hb" }, channel: { snrDb: 40 }, set: { overscan: 0.04 }, view: { mode: "closeup" }, display: { tube: "slot", screenIn: 20 } } },
  { id: "uk-eng-betacam-1989", group: "UK broadcast", title: "News on Betacam SP, 1989", evidence: "research",
    note: "CCD camera on Betacam SP (component, ~4.5 MHz luma, 1.5 MHz colour).",
    s: { standard: "PAL-I", camera: { type: "ccd3_broadcast" }, recording: { format: "betacam_sp" }, channel: { snrDb: 42 }, set: { overscan: 0.04 }, view: { mode: "closeup" }, display: { tube: "slot", screenIn: 21 } } },
  { id: "uk-sky-1990", group: "UK broadcast", title: "Sky on Astra, 1990", evidence: "research",
    note: "Analogue PAL over an FM satellite link, so all PAL artefacts remain; sparklies appear on a weak dish. Satellite noise amounts are estimates.",
    s: { standard: "PAL-I", camera: { type: "ccd3_broadcast" }, channel: { route: "sat_fm", cnrDb: 11 }, set: { overscan: 0.04 }, view: { mode: "closeup" }, display: { tube: "slot", screenIn: 21 } } },
  { id: "uk-bsb-1990", group: "UK broadcast", title: "BSB D-MAC, 1990", evidence: "research",
    note: "BSB's D-MAC: no subcarrier, so no cross-colour or dot crawl; sharper colour across, half the colour detail down. Bandwidths estimated from the compression ratios.",
    s: { standard: "PAL-I", camera: { type: "ccd3_broadcast" }, channel: { route: "dmac", snrDb: 44 }, set: { overscan: 0.04 }, view: { mode: "closeup" }, display: { tube: "slot", screenIn: 21 } } },
  // ---------------- US broadcast
  { id: "us-live-1950", group: "US broadcast", title: "US live TV, 1950", evidence: "spec",
    note: "525-line monochrome from an image orthicon (dark halo round highlights), 4.2 MHz, on a 17in set. Live pictures survive mainly as kinescopes.",
    s: { standard: "525-MONO", camera: { type: "io_mono" }, channel: { snrDb: 34 }, set: { overscan: 0.05, sharpness: 0.2 }, view: { mode: "closeup" }, display: { tube: "mono", screenIn: 17 } } },
  { id: "us-kinescope-1952", group: "US broadcast", title: "US kinescope, 1952", evidence: "research",
    note: "525/60 filmed at 24 fps; a drifting shutter leaves a brighter band. 16 mm grain and ~40:1 range.",
    s: { standard: "525-MONO", camera: { type: "io_mono" }, transfer: { type: "telerecord", method: "kinescope", gauge: 16, shutterBar: 0.35 }, enabled: { channel: false } } },
  { id: "us-rca-colour-1958", group: "US broadcast", title: "Early RCA colour, 1958", evidence: "research",
    note: "3-tube image orthicon colour camera, NTSC with the 1953 primaries on a delta-gun set; equal-band colour decoding.",
    s: { standard: "NTSC-M", camera: { type: "io_colour" }, recording: { format: "quad_hb" }, channel: { snrDb: 36 }, decoder: { separation: "notch", ntscDemod: "equiband" }, set: { overscan: 0.05 }, view: { mode: "closeup" }, display: { tube: "delta", screenIn: 21, primaries: "NTSC1953", white: "C" } } },
  { id: "us-sitcom-1975", group: "US broadcast", title: "US network sitcom, 1975", evidence: "research",
    note: "Multi-camera Plumbicon studio on Quad, NTSC, on a slot-mask set at 9300 K. Its famous 'video look' is mostly 60-field motion, which a still cannot show.",
    s: { standard: "NTSC-M", camera: { type: "plumbicon3", overrides: { gamma: "bt709" } }, recording: { format: "quad_hb" }, channel: { snrDb: 40 }, decoder: { separation: "notch", ntscDemod: "equiband", phaseErr: 4 }, set: { overscan: 0.05, sharpness: 0.2 }, view: { mode: "closeup" }, display: { tube: "slot", screenIn: 19, primaries: "SMPTEC", white: "K9300" } } },
  { id: "us-news-1985", group: "US broadcast", title: "US local news, 1985", evidence: "research",
    note: "Tube ENG camera on U-matic, NTSC over the air.",
    s: { standard: "NTSC-M", camera: { type: "plumbicon3", overrides: { noiseDb: 36, contour: 0.55, gamma: "bt709" } }, recording: { format: "umatic_hb" }, channel: { snrDb: 38 }, decoder: { separation: "notch", ntscDemod: "equiband" }, set: { overscan: 0.05 }, view: { mode: "closeup" }, display: { tube: "slot", screenIn: 19, primaries: "SMPTEC", white: "K9300" } } },
  // ---------------- France
  { id: "fr-819-1960", group: "France", title: "French 819-line TV, 1960", evidence: "spec",
    note: "RTF 819 lines, 10 MHz: the sharpest broadcast standard before HD. Camera type not found; an image orthicon is assumed.",
    s: { standard: "819-E", camera: { type: "io_mono" }, channel: { snrDb: 36 }, set: { overscan: 0.04 }, view: { mode: "closeup" }, display: { tube: "mono", screenIn: 17 } } },
  { id: "fr-secam-1975", group: "France", title: "ORTF SECAM colour, 1975", evidence: "research",
    note: "SECAM L: FM colour on alternate lines (half the colour detail down, streaks on colour edges). Studios often worked in PAL or component and coded SECAM for transmission.",
    s: { standard: "SECAM-L", camera: { type: "plumbicon3" }, channel: { snrDb: 38 }, set: { overscan: 0.04 }, view: { mode: "closeup" }, display: CRT_UK } },
  // ---------------- Home video
  { id: "vhs-offair-1986", group: "Home video", title: "VHS off-air recording, 1986 (UK)", evidence: "research",
    note: "A broadcast recorded on a home VHS at SP from an aerial with a faint ghost, as a frame-grab.",
    s: { standard: "PAL-I", camera: { type: "plumbicon3" }, channel: { snrDb: 37, ghosts: [{ delayUs: 1.5, amp: 0.1, phaseDeg: 0 }] }, recording: { format: "vhs_sp", position: "home" }, view: { mode: "grab" } } },
  { id: "vhs-copy-1990", group: "Home video", title: "VHS third-generation copy", evidence: "research",
    note: "An off-air LP recording copied twice more: noise, smear and wobble build up with each generation.",
    s: { standard: "PAL-I", camera: { type: "plumbicon3" }, channel: { snrDb: 38 }, recording: { format: "vhs_lp", position: "home", generations: 3 }, view: { mode: "grab" } } },
  { id: "vhs-us-1988", group: "Home video", title: "VHS off-air recording, 1988 (US)", evidence: "research",
    note: "NTSC VHS SP off-air, frame-grab.",
    s: { standard: "NTSC-M", camera: { type: "plumbicon3", overrides: { gamma: "bt709" } }, channel: { snrDb: 37 }, recording: { format: "vhs_sp", position: "home" }, decoder: { ntscDemod: "equiband" }, view: { mode: "grab" } } },
  { id: "betamax-1981", group: "Home video", title: "Betamax off-air, 1981", evidence: "research",
    note: "Betamax recording of a broadcast. Betamax figures are estimates.",
    s: { standard: "PAL-I", camera: { type: "plumbicon3" }, channel: { snrDb: 38 }, recording: { format: "betamax", position: "home" }, view: { mode: "grab" } } },
  { id: "camcorder-tube-1984", group: "Home video", title: "Tube camcorder, 1984", evidence: "research",
    note: "Single Saticon tube (lag, orange-red flare, soft colour) recording to VHS-C.",
    s: { standard: "PAL-I", camera: { type: "saticon_camcorder" }, recording: { format: "vhs_sp" }, enabled: { channel: false }, view: { mode: "grab" } } },
  { id: "video8-1988", group: "Home video", title: "Video8 camcorder, 1988", evidence: "research",
    note: "Single-CCD consumer camcorder on Video8 (vertical smear on highlights).",
    s: { standard: "PAL-I", camera: { type: "ccd1_consumer" }, recording: { format: "video8" }, enabled: { channel: false }, view: { mode: "grab" } } },
  { id: "hi8-1994", group: "Home video", title: "Hi8 camcorder, 1994", evidence: "research",
    note: "Sharper Hi8 luma, same narrow colour.",
    s: { standard: "PAL-I", camera: { type: "ccd1_consumer" }, recording: { format: "hi8" }, enabled: { channel: false }, view: { mode: "grab" } } },
  { id: "svhs-1992", group: "Home video", title: "S-VHS camcorder, 1992", evidence: "research",
    note: "S-VHS: sharp luma, VHS colour.",
    s: { standard: "PAL-I", camera: { type: "ccd1_consumer" }, recording: { format: "svhs" }, enabled: { channel: false }, view: { mode: "grab" } } },
  { id: "minidv-2002", group: "Home video", title: "MiniDV, 2002 (PAL)", evidence: "research",
    note: "3-CCD DV camcorder: 4:2:0 colour, 8×8 DCT blocks and mosquito noise at 25 Mbit/s, hard highlight clip.",
    s: { standard: "COMP-625", camera: { type: "dv3ccd" }, recording: { format: "dv_pal" }, enabled: { encoder: false }, view: { mode: "grab" } } },
  { id: "minidv-ntsc-2002", group: "Home video", title: "MiniDV, 2002 (NTSC)", evidence: "research",
    note: "NTSC DV: 4:1:1 colour (only 180 colour samples across).",
    s: { standard: "COMP-525", camera: { type: "dv3ccd" }, recording: { format: "dv_ntsc" }, enabled: { encoder: false }, view: { mode: "grab" } } },
  // ---------------- Archive and transfers
  { id: "us-on-bbc-1970", group: "Archive and transfers", title: "US show on the BBC, 1970", evidence: "research",
    note: "NTSC converted to PAL by the BBC's 1967 field-store converter: picture inset with black borders; with implied motion, one field in five is a double image.",
    s: { standard: "NTSC-M", camera: { type: "plumbicon3", overrides: { gamma: "bt709" } }, recording: { format: "quad_hb" }, transfer: { type: "convert", method: "bbc1967", target: "PAL-I" }, channel: { snrDb: 40 }, set: { overscan: 0.04 }, view: { mode: "closeup" }, display: CRT_UK } },
  { id: "uk-in-us-1985", group: "Archive and transfers", title: "UK show on US TV, 1985", evidence: "research",
    note: "PAL converted to NTSC by a digital four-field converter.",
    s: { standard: "PAL-I", camera: { type: "emi2001" }, transfer: { type: "convert", method: "digital", target: "NTSC-M" }, channel: { snrDb: 40 }, decoder: { separation: "notch", ntscDemod: "equiband" }, set: { overscan: 0.05 }, view: { mode: "closeup" }, display: { tube: "slot", screenIn: 19, primaries: "SMPTEC", white: "K9300" } } },
  { id: "optical-converter-1962", group: "Archive and transfers", title: "Optical standards conversion, 1962", evidence: "research",
    note: "A camera pointed at a monitor: the source scan lines beat against the new ones.",
    s: { standard: "NTSC-M", camera: { type: "io_colour" }, transfer: { type: "convert", method: "optical", target: "PAL-I" }, channel: { snrDb: 38 }, view: { mode: "grab" } } },
  { id: "pal60-tape", group: "Archive and transfers", title: "NTSC tape on a UK VCR (PAL-60)", evidence: "research",
    note: "An American VHS played on a UK machine that outputs PAL-60: correct colour, but only 480 lines, so the line structure is coarser.",
    s: { standard: "NTSC-M", camera: { type: "plumbicon3" }, recording: { format: "vhs_sp" }, transfer: { type: "crossplay", mode: "pal60" }, enabled: { channel: false }, set: { overscan: 0.04 }, view: { mode: "closeup" }, display: { tube: "slot", screenIn: 21 } } },
  { id: "ntsc443-tape", group: "Archive and transfers", title: "NTSC 4.43 on a PAL-only set", evidence: "research",
    note: "NTSC colour on the PAL subcarrier has no V switch, so a PAL set's delay line cancels half the colour: reds turn dark.",
    s: { standard: "NTSC-M", camera: { type: "plumbicon3" }, recording: { format: "vhs_sp" }, transfer: { type: "crossplay", mode: "ntsc443" }, enabled: { channel: false }, view: { mode: "grab" } } },
  { id: "secam-on-pal-set", group: "Archive and transfers", title: "SECAM tape on a PAL-only set", evidence: "research",
    note: "No SECAM decoder: black and white, with the FM subcarrier showing as a dot pattern even on greys.",
    s: { standard: "SECAM-L", camera: { type: "plumbicon3" }, transfer: { type: "crossplay", mode: "secam_mono" }, enabled: { channel: false }, set: { overscan: 0.04 }, view: { mode: "closeup" }, display: { tube: "slot", screenIn: 21 } } },
  { id: "telecine-us-32", group: "Archive and transfers", title: "US film telecine with 3:2 pulldown", evidence: "research",
    note: "Film on NTSC: two frames in five mix two film frames. Set Implied motion to see the combing.",
    s: { standard: "NTSC-M", transfer: { type: "telecine", pulldown: "mixed" }, motion: { px: 4, angle: 0 }, decoder: { separation: "comb1H", ntscDemod: "equiband" }, view: { mode: "grab", deinterlace: "weave" } } },
  { id: "screen-photo-1978", group: "Archive and transfers", title: "Photo of the TV screen, 1978", evidence: "research",
    note: "A UK colour broadcast photographed off a slot-mask set at 1/125 s: the exposure catches only part of the scan, so a band is brighter.",
    s: { standard: "PAL-I", camera: { type: "emi2001" }, recording: { format: "quad_hb" }, channel: { snrDb: 40 }, set: { overscan: 0.04 }, view: { mode: "photo", exposure: 0.62, bandPos: 0.4, focus: 0.8, reflection: 0.5, grain: 0.5 }, display: { tube: "slot", screenIn: 22 } } },

  // ================= v1.1 =================
  // ---------------- Long-distance reception (research H: Bunney 1981, Television magazine, BT.470-6)
  { id: "dx-holland-1983", group: "Long-distance reception", title: "Summer lift: Dutch TV on a UK set, 1983", evidence: "research",
    note: "Nederland 1 or 2 (Goes, Lopik) across the North Sea under a summer high. Dutch System G PAL: full colour, no sound on a UK set, and the 5.5 MHz Dutch sound carrier leaves fine patterning. A weak co-channel station floats underneath, striped by the carrier offset. The mechanisms are documented; the amounts (signal level, interference) are yours to set. For a real second picture, name a layer 'second picture'.",
    s: { standard: "PAL-BG", camera: { type: "plumbicon3" }, channel: { snrDb: 27, cochannel: { ratio: 0.14, offsetHz: 10400, dx: 0.31, dy: 0.37, source: "mirror" } }, receiver: { standard: "PAL-I" }, set: { overscan: 0.04, sharpness: 0.1 }, view: { mode: "closeup" }, display: { tube: "slot", screenIn: 22, primaries: "EBU", white: "D65" } } },
  { id: "dx-belgium-1984", group: "Long-distance reception", title: "Belgian RTBF on a UK set, 1984", evidence: "research",
    note: "RTBF 1 or Télé 2 on a good lift: Belgian PAL (System H on UHF, 5.5 MHz sound), so colour but silence on a UK set, with faint sound-carrier patterning. Signal level [EST].",
    s: { standard: "PAL-BG", camera: { type: "plumbicon3" }, channel: { snrDb: 33 }, receiver: { standard: "PAL-I" }, set: { overscan: 0.04, sharpness: 0.1 }, view: { mode: "closeup" }, display: { tube: "slot", screenIn: 22, primaries: "EBU", white: "D65" } } },
  { id: "dx-france-1983", group: "Long-distance reception", title: "French TV (TF1, Antenne 2) on a UK set, 1983", evidence: "research",
    note: "France's System L puts the picture on the carrier the other way up (positive modulation), so a UK set shows a negative; its SECAM colour is lost; and the set can't find the French sync, so the picture tears sideways and rolls, with the blanking showing as white bars. Built from the ITU levels and receiver behaviour; no off-screen photos checked. New noise gives another moment; Vertical hold 'rolling' and Roll position move the bar.",
    s: { standard: "SECAM-L", camera: { type: "plumbicon3" }, channel: { snrDb: 28 }, receiver: { standard: "PAL-I" }, set: { overscan: 0.04 }, view: { mode: "closeup" }, display: { tube: "slot", screenIn: 22, primaries: "EBU", white: "D65" } } },
  { id: "canal-plus-1984", group: "Long-distance reception", title: "Canal+ without a decoder, 1984", evidence: "research",
    note: "Canal+ (from 4 Nov 1984) scrambled with Discret 11: every line delayed by 0, 0.9 or 1.8 µs at random, black filling the gap. Shown on a French SECAM set. The delays are documented; the pseudo-random sequence here is VideoLook's own.",
    s: { standard: "SECAM-L", camera: { type: "ccd3_broadcast" }, channel: { snrDb: 40, scramble: "discret11" }, set: { overscan: 0.04 }, view: { mode: "closeup" }, display: { tube: "slot", screenIn: 22, primaries: "EBU", white: "D65" } } },
  { id: "dx-sporadic-e", group: "Long-distance reception", title: "Sporadic-E on Band I, DXer's portable, 1978", evidence: "research",
    note: "A distant continental Band I station by Sporadic-E (May to September, 500-1,400 miles) on a black-and-white portable: snow, a long echo, and a second station on the same channel sliding across. Mechanisms from Bunney (1981); all amounts [EST].",
    s: { standard: "PAL-BG", camera: { type: "plumbicon3" }, channel: { snrDb: 21, ghosts: [{ delayUs: 6, amp: 0.22, phaseDeg: 90 }], cochannel: { ratio: 0.3, offsetHz: 7800, dx: 0.6, dy: 0.2, source: "mirror" } }, receiver: { standard: "same" }, decoder: { separation: "none" }, set: { overscan: 0.05, sharpness: 0.1 }, view: { mode: "closeup" }, display: { tube: "mono", screenIn: 12 } } },
  { id: "uk-lockout", group: "Long-distance reception", title: "Overloaded set near a transmitter (lockout)", evidence: "research",
    note: "Too much signal: the set's IF stage overloads and the sync tips are crushed below the picture: 'lockout, i.e. negative picture and buzz' (Television, July 1976). One source; the overload curve is [EST].",
    s: { standard: "PAL-I", camera: { type: "emi2001" }, channel: { snrDb: 48 }, receiver: { overload: 0.55 }, set: { overscan: 0.04 }, view: { mode: "closeup" }, display: { tube: "slot", screenIn: 22 } } },
  // ---------------- USSR and Eastern Europe
  { id: "su-343-1938", group: "USSR and Eastern Europe", title: "Moscow 343-line, 1938", evidence: "spec",
    note: "343 lines at 25 frames on RCA equipment (from 1938; dates conflict). Bandwidth 3.29 MHz and negative modulation are RCA's figures from a single source; an iconoscope camera is assumed.",
    s: { standard: "343-RU", camera: { type: "emitron" }, channel: { snrDb: 33 }, set: { overscan: 0.05, sharpness: 0.1 }, view: { mode: "closeup" }, display: { tube: "mono", screenIn: 12 } } },
  { id: "su-kvn49-1950", group: "USSR and Eastern Europe", title: "Soviet 625-line on a KVN-49 with its water lens, 1950", evidence: "research",
    note: "The Soviet Union's own 625-line standard (the one Europe adopted), 6 MHz, on the KVN-49: a 140 x 105 mm picture on an 18 cm round tube, seen through the add-on lens filled with water or glycerine (about 4x). The lens's distortion, fringing and reflection are [EST]; the studio camera is not researched (an iconoscope is assumed).",
    s: { standard: "625-DK-MONO", camera: { type: "emitron", overrides: { shading: 0.06 } }, channel: { snrDb: 36 }, set: { overscan: 0.04, sharpness: 0.1 }, view: { mode: "lens" }, display: { tube: "mono", screenIn: 7, roundScreen: 1.02, roundCorner: 0.12, barrel: 0.04 } } },
  { id: "su-rubin-1978", group: "USSR and Eastern Europe", title: "Soviet colour on a Rubin set, late 1970s", evidence: "research",
    note: "SECAM on System D/K from 1 Oct 1967: the same colour coding as France but the ordinary negative modulation, so interference makes dark spots. Soviet tube phosphors per GOST 26799-85 are the EBU set. Camera assumed.",
    s: { standard: "SECAM-DK", camera: { type: "plumbicon3" }, channel: { snrDb: 37, impulses: 0.02 }, set: { overscan: 0.04, sharpness: 0.15 }, view: { mode: "closeup" }, display: { tube: "delta", screenIn: 24, primaries: "EBU", white: "D65" } } },
  { id: "ddr-secam-1975", group: "USSR and Eastern Europe", title: "East German SECAM colour, 1975", evidence: "research",
    note: "DFF colour from 1969: SECAM on System B/G (5 MHz), until the switch to PAL at the end of 1991. East German set phosphors not found; EBU assumed.",
    s: { standard: "SECAM-BG", camera: { type: "plumbicon3" }, channel: { snrDb: 40 }, set: { overscan: 0.04, sharpness: 0.1 }, view: { mode: "closeup" }, display: { tube: "delta", screenIn: 22, primaries: "EBU", white: "D65" } } },
  // ---------------- Japan
  { id: "jp-ntsc-1985", group: "Japan", title: "Japanese NTSC on a 9300 K set, 1985", evidence: "research",
    note: "NTSC-J: black sits at blanking (no 7.5% set-up), and receivers were set to 9300 K + 27 MPCD, a cool, slightly green white (x 0.281, y 0.311). Receiver phosphors from a 1979 Matsushita patent. Many real sets measured nearer 8500-8800 K.",
    s: { standard: "NTSC-J", camera: { type: "plumbicon3", overrides: { gamma: "bt709" } }, channel: { snrDb: 42 }, decoder: { separation: "notch", ntscDemod: "equiband" }, set: { overscan: 0.05 }, view: { mode: "closeup" }, display: { tube: "trinitron", screenIn: 21, primaries: "P22J", white: "K9300_27" } } },
  { id: "jp-hivision-1991", group: "Japan", title: "Hi-Vision (MUSE) analogue HD, 1991", evidence: "research",
    note: "NHK's 1125-line analogue HD by satellite (1989-2007). Still pictures keep ~598 lines of detail, but anything moving drops to about a quarter: set Implied motion and tick 'Only the selection moves' to see it (camera pans stay sharp). No camera stage: HD cameras aren't modelled.",
    s: { standard: "MUSE", aspect: 16 / 9, channel: { snrDb: 46 }, set: { overscan: 0.02 }, view: { mode: "closeup" }, display: { tube: "trinitron", screenIn: 36, primaries: "SMPTEC", white: "D65" } } },
  { id: "jp-cv2000-1966", group: "Japan", title: "Sony CV-2000 home video, 1966", evidence: "research",
    note: "One of the first home video recorders: half-inch tape, black and white, recording only one field and showing it twice (skip-field), about 220 lines. With a vidicon camera.",
    s: { standard: "525-MONO", camera: { type: "vidicon", overrides: { mono: true, tubes: 1 } }, recording: { format: "cv2000" }, enabled: { channel: false }, view: { mode: "closeup" }, display: { tube: "mono", screenIn: 11 } } },
  { id: "portapak-1970", group: "Japan", title: "Sony Portapak video art, 1970", evidence: "research",
    note: "EIAJ-1 half-inch reel recorder and vidicon camera (needed about 50 foot-candles): black and white, laggy, noisy, with 'flagging' at the top on replay. European (625) version.",
    s: { standard: "625-MONO", camera: { type: "vidicon_portapak" }, recording: { format: "eiaj1" }, enabled: { channel: false }, view: { mode: "closeup" }, display: { tube: "mono", screenIn: 12 } } },
  // ---------------- Early television
  { id: "baird-30-1933", group: "Early television", title: "Baird 30-line on a Televisor, 1933", evidence: "research",
    note: "The BBC's 30-line service (to 1935): 30 vertical lines, 12.5 pictures a second, a tall 3:7 picture sent on a medium-wave channel (~10 kHz), seen as an orange neon glow through a spinning disc, 'about the size of a postage stamp'. Off-air recordings survive at tvdawn.com for comparison.",
    s: { standard: "30-BAIRD", aspect: 3 / 7, channel: { snrDb: 32 }, view: { mode: "televisor" } } },
  { id: "baird-240-1936", group: "Early television", title: "Baird 240-line intermediate film, 1936", evidence: "spec",
    note: "Alexandra Palace, Nov 1936-Feb 1937, alternating with EMI's 405 lines: shot on film, developed in about a minute and scanned wet. 240 lines at 25 frames; bandwidth and picture shape not found (4:3 and equal detail assumed). No pictures survive.",
    s: { standard: "240-BAIRD", camera: { type: "intermediate_film" }, channel: { snrDb: 30 }, set: { overscan: 0.03 }, view: { mode: "closeup" }, display: { tube: "mono", screenIn: 12 } } },
  { id: "de-441-1938", group: "Early television", title: "Berlin 441-line, 1938", evidence: "spec",
    note: "Fernsehsender Paul Nipkow: 441 lines interlaced (383 active), 2 MHz, positive modulation, a nearly square 1.15:1 picture (single source). Iconoscope camera.",
    s: { standard: "441-DE", aspect: 1.15, camera: { type: "emitron" }, channel: { snrDb: 32 }, set: { overscan: 0.04, sharpness: 0.1 }, view: { mode: "closeup" }, display: { tube: "mono", screenIn: 12 } } },
  { id: "us-441-1940", group: "Early television", title: "NBC 441-line, 1940", evidence: "spec",
    note: "The pre-war American standard (1939-41): 441 lines, 60 fields, 2.8 MHz, negative modulation (single source). RCA iconoscope camera.",
    s: { standard: "441-US", camera: { type: "emitron" }, channel: { snrDb: 32 }, set: { overscan: 0.04, sharpness: 0.1 }, view: { mode: "closeup" }, display: { tube: "mono", screenIn: 12 } } },
  { id: "cbs-colour-1951", group: "Early television", title: "CBS field-sequential colour, 1951", evidence: "spec",
    note: "Broadcast June-October 1951: 405 lines, 144 fields a second, each field one colour, put back together by a spinning colour wheel in front of a black-and-white tube. About half the horizontal detail of ordinary 525-line. Set Implied motion to see colours split apart on movement. Filter colours [EST].",
    s: { standard: "405-CBS", camera: { type: "io_colour", overrides: { tubes: 1 } }, channel: { snrDb: 36 }, set: { overscan: 0.04 }, view: { mode: "closeup" }, display: { tube: "wheel", screenIn: 12, primaries: "NTSC1953", white: "C", maskStrength: 0 } } },
  { id: "be-819-1955", group: "Early television", title: "Belgian 819-line, 1955", evidence: "spec",
    note: "Belgium's 819-line System F (1953-68) squeezed the French line count into 7 MHz channels: ~5 MHz of video (sources say 5 or 5.5), so far less horizontal detail than French 819.",
    s: { standard: "819-F", camera: { type: "io_mono" }, channel: { snrDb: 36 }, set: { overscan: 0.04 }, view: { mode: "closeup" }, display: { tube: "mono", screenIn: 17 } } },
  // ---------------- Space, surveillance and toys
  { id: "apollo11-1969", group: "Space, surveillance and toys", title: "Apollo 11 moonwalk as broadcast, 1969", evidence: "research",
    note: "The lunar camera sent 320 lines at 10 frames a second; on Earth an RCA TK-22 camera re-shot a 10-inch monitor to make NTSC, losing contrast and detail, and the monitor's persistence left moving figures trailing ghosts (needs Implied motion). Honeysuckle Creek settings; set Converter contrast up for Goldstone's over-contrasty picture.",
    s: { standard: "320-APOLLO", camera: { type: "apollo_sec" }, transfer: { type: "convert", method: "optical", target: "525-MONO", cameraMono: true, lag: 0.55, contrast: 1.0 }, channel: { snrDb: 34 }, set: { overscan: 0.05 }, view: { mode: "closeup" }, display: { tube: "mono", screenIn: 19 } } },
  { id: "pixelvision-1988", group: "Space, surveillance and toys", title: "Fisher-Price Pixelvision, 1988", evidence: "research",
    note: "The PXL-2000 toy camcorder: a 120 x 90 CCD recorded on audio cassette at 9x speed, black and white with only a few grey levels (one source says about 8), shown small in the middle of the TV. Inset size and noise [EST].",
    s: { standard: "525-MONO", camera: { type: "pxl2000" }, recording: { format: "pxl_cassette" }, enabled: { channel: false }, set: { overscan: 0.05 }, view: { mode: "closeup" }, display: { tube: "slot", screenIn: 13, primaries: "SMPTEC", white: "K9300" } } },
  { id: "cctv-1994", group: "Space, surveillance and toys", title: "Time-lapse CCTV, 1994", evidence: "research",
    note: "A black-and-white CCTV camera on a time-lapse VHS in 24-hour mode (5 fields a second, 300 lines), date and time burned in, replayed as a single field. Recorder figures from a period manual; the rest [EST]. Edit the stamp under Overlay.",
    s: { standard: "625-MONO", camera: { type: "cctv_ccd" }, overlay: { kind: "timestamp", text: "CAM 3\n14-09-94  23:41:07", pos: "bl" }, recording: { format: "tl_vhs" }, enabled: { channel: false }, view: { mode: "grab" } } },
  { id: "sstv-1958", group: "Space, surveillance and toys", title: "Amateur slow-scan TV on a radar tube, 1958", evidence: "research",
    note: "Copthorne Macdonald's 1958 slow-scan TV: 120 lines, 8 seconds a picture, sent as audio over short-wave, shown on a P7 radar tube whose blue flash fades to a yellow-green afterglow lasting about 10 s, so the top of the picture has already faded as the bottom is written. Afterglow colours [EST].",
    s: { standard: "120-SSTV", aspect: 1, channel: { snrDb: 22, impulses: 0.04 }, view: { mode: "closeup" }, display: { tube: "p7", screenIn: 7, roundScreen: 0.86, frameSec: 8, tauSec: 10, writePos: 1.0, spot: 0.4, bloom: 0.3, barrel: 0.01, roundCorner: 0 } } },
  // ---------------- South America
  { id: "br-palm-1985", group: "South America", title: "Brazilian PAL-M, 1985", evidence: "research",
    note: "Brazil's PAL-M (colour from 1972): American 525/60 scanning with PAL colour on its own 3.576 MHz subcarrier, so no NTSC hue errors but 4.2 MHz of detail and the 7.5% set-up. Set phosphors assumed.",
    s: { standard: "PAL-M", camera: { type: "plumbicon3", overrides: { gamma: "bt709" } }, channel: { snrDb: 40 }, decoder: { palMode: "delay" }, set: { overscan: 0.05 }, view: { mode: "closeup" }, display: { tube: "slot", screenIn: 20, primaries: "SMPTEC", white: "C" } } },
  { id: "ar-paln-1985", group: "South America", title: "Argentine PAL-N, 1985", evidence: "research",
    note: "Argentina's N/PAL: European 625/50 in American 6 MHz channels, 4.2 MHz of video and a 3.58 MHz PAL subcarrier nearer the luma, so softer and with more cross-colour than European PAL. Black at blanking (no set-up).",
    s: { standard: "PAL-N", camera: { type: "plumbicon3" }, channel: { snrDb: 40 }, decoder: { palMode: "delay" }, set: { overscan: 0.05 }, view: { mode: "closeup" }, display: { tube: "slot", screenIn: 20, primaries: "EBU", white: "D65" } } },
  // ---------------- Discs
  { id: "laserdisc-1990", group: "Home video", title: "LaserDisc (PAL, CLV crosstalk), 1990", evidence: "research",
    note: "A film on a long-play (CLV) LaserDisc: full broadcast detail on an optical disc, but crosstalk from the neighbouring track drifts through as bands of fine noise ('barber poles'). Crosstalk form and amount [EST].",
    s: { standard: "PAL-I", transfer: { type: "telecine" }, recording: { format: "laserdisc" }, enabled: { channel: false }, decoder: { separation: "comb2H" }, set: { overscan: 0.04 }, view: { mode: "closeup" }, display: { tube: "trinitron", screenIn: 25, primaries: "EBU", white: "D65" } } },
  { id: "laserdisc-rot", group: "Home video", title: "LaserDisc with laser rot", evidence: "research",
    note: "An oxidised disc: sparkling specks, some coloured, some dark, scattered over the picture. Density [EST].",
    s: { standard: "PAL-I", transfer: { type: "telecine" }, recording: { format: "laserdisc_rot" }, enabled: { channel: false }, decoder: { separation: "comb2H" }, set: { overscan: 0.04 }, view: { mode: "grab" } } },
  { id: "ced-1983", group: "Home video", title: "RCA CED videodisc, worn (1983)", evidence: "research",
    note: "RCA's grooved capacitance disc: 3 MHz of detail, narrow colour, and dust and wear ('video virus') giving dropouts and snow. How the colour was carried isn't confirmed; modelled as a narrow colour band.",
    s: { standard: "NTSC-M", transfer: { type: "telecine" }, recording: { format: "ced" }, enabled: { channel: false }, decoder: { separation: "notch", ntscDemod: "equiband" }, set: { overscan: 0.05 }, view: { mode: "closeup" }, display: { tube: "slot", screenIn: 19, primaries: "SMPTEC", white: "K9300" } } },
  // ---------------- Teletext
  { id: "uk-teletext-mix-1983", group: "UK broadcast", title: "Teletext page mixed over the picture, 1983", evidence: "research",
    note: "The set's teletext decoder writing a page over the programme ('mix'): 24 rows of 40 characters on the 6 MHz dot clock, rounded characters, eight colours. The font is VideoLook's own; the page text is invented and editable under Overlay.",
    s: { standard: "PAL-I", camera: { type: "emi2001" }, channel: { snrDb: 42 }, overlay: { kind: "teletext", mode: "mix", header: "P102  TELETEXT 102  Mon 12 Sep  18:42/07",
      text: "{yellow}{dh}   NEWS IN BRIEF\n\n{cyan} 103 {white}Heatwave holds on the east coast\n{cyan} 104 {white}Harbour reopens after gales\n{cyan} 105 {white}Village fete raises record sum\n\n{green} WEATHER  {white}Sunny spells, 23C    {yellow}400\n{magenta} SPORT    {white}Cycling: stage 14     {yellow}300" },
      set: { overscan: 0.04 }, view: { mode: "closeup" }, display: { tube: "slot", screenIn: 22 } } },
  { id: "uk-subtitles-1985", group: "UK broadcast", title: "Teletext subtitles, 1985", evidence: "research",
    note: "Page 888-style subtitles: double-height text in black boxes, white first then yellow, cyan and green for other speakers. Text invented and editable under Overlay.",
    s: { standard: "PAL-I", camera: { type: "emi2001" }, channel: { snrDb: 42 }, overlay: { kind: "teletext", mode: "subtitle", colour: "white", text: "{yellow}Did you see it again last night?\n{white}Only when the weather was right." },
      set: { overscan: 0.04 }, view: { mode: "closeup" }, display: { tube: "slot", screenIn: 22 } } },
  // ---------------- Community TV and video art (v1.1.6; research J)
  { id: "swindon-viewpoint-1974", group: "Community TV and video art", title: "Swindon Viewpoint, 1974 (black-and-white cable)", evidence: "research",
    note: "Britain's community cable station (from Sept 1973, EMI-funded, on the Radio Rentals relay network). Until 1977 it was black and white: Sony Portapaks and 1-inch Sony recorders, low light on location, copy-edited with a glitch at each edit, then carried cleanly by cable. The half-inch Portapak format stands in for both machines; the haloes come from the set's sharpness control here, which is [EST].",
    s: { standard: "625-MONO", camera: { type: "vidicon_portapak" }, recording: { format: "eiaj1" }, channel: { snrDb: 44 }, set: { overscan: 0.04, sharpness: 0.45 }, view: { mode: "closeup" }, display: { tube: "mono", screenIn: 22 } } },
  { id: "swindon-viewpoint-1978", group: "Community TV and video art", title: "Swindon Viewpoint, 1978 (colour U-matic)", evidence: "research",
    note: "From 1977 the station moved to colour: U-matic recorders and single-tube Sony cameras, and by its own account 'picture quality, or at least resolution, went down somewhat with the move to colour'. Single-tube camera model stands in [EST].",
    s: { standard: "PAL-I", camera: { type: "saticon_camcorder", overrides: { gamma: "power045" } }, recording: { format: "umatic_lb" }, channel: { snrDb: 43 }, set: { overscan: 0.04, sharpness: 0.3 }, view: { mode: "closeup" }, display: { tube: "slot", screenIn: 22 } } },
  { id: "tv-receiver-generations", group: "Community TV and video art", title: "Re-shot off a monitor, again and again", evidence: "research",
    note: "After David Hall's 'This Is A Television Receiver' (BBC, 1976), where a newsreader was re-shot off a monitor, each copy from the last, 'until there is a complete degeneration of both sound and image'. Set Conversion generations under Transfer (1-12). The monitor-and-camera model is the optical converter's [EST].",
    s: { standard: "PAL-I", camera: { type: "plumbicon3" }, transfer: { type: "convert", method: "optical", target: "PAL-I", generations: 6 }, channel: { snrDb: 42 }, set: { overscan: 0.04 }, view: { mode: "closeup" }, display: { tube: "slot", screenIn: 22 } } },
  { id: "electronovision-1964", group: "Community TV and video art", title: "Videotape to cinema film, 1964 (Electronovision-style)", evidence: "research",
    note: "Before 200 Motels, Electronovision shot plays and concerts on videotape and moved them to film by kinescope for cinemas (Hamlet, The T.A.M.I. Show, 1964). A US colour-era camera on Quad, filmed off a monitor at 24 frames.",
    s: { standard: "525-MONO", camera: { type: "io_mono" }, recording: { format: "quad_hb" }, transfer: { type: "telerecord", method: "kinescope", gauge: 35, shutterBar: 0.2 }, enabled: { channel: false } } },
  // ---------------- Subtitles (v1.1.1; sources in vl_text.js and research I)
  { id: "sub-bbc2-1988", group: "Subtitles", title: "Foreign film on BBC2, late 1980s", evidence: "research",
    note: "A subtitled film through a flying-spot telecine, with the BBC's slab-serif subtitles (TKST, 'based at many removes on Rockwell Light', 1975-77) added at the studio with a black edge. TKST isn't available, so Rockwell stands in. Run FilmLook first for the film stock. Edit the text under Overlay.",
    s: { standard: "PAL-I", transfer: { type: "telecine" }, overlay: { kind: "subtitle", style: "bbc_edge", text: "Where were you on the night of the storm?\nAt the lighthouse, as always." }, channel: { snrDb: 42 }, set: { overscan: 0.04 }, view: { mode: "closeup" }, display: { tube: "slot", screenIn: 22 } } },
  { id: "sub-bbc-label", group: "Subtitles", title: "BBC subtitles on a grey label", evidence: "research",
    note: "The BBC's later fix for edging problems: the picture darkened and its colour killed in a rectangle behind the text (the designer's own account; single source).",
    s: { standard: "PAL-I", transfer: { type: "telecine" }, overlay: { kind: "subtitle", style: "bbc_label", text: "Where were you on the night of the storm?\nAt the lighthouse, as always." }, channel: { snrDb: 42 }, set: { overscan: 0.04 }, view: { mode: "closeup" }, display: { tube: "slot", screenIn: 22 } } },
  { id: "sub-arthouse-print", group: "Subtitles", title: "Arthouse print with laser subtitles, 1990s", evidence: "research",
    note: "Subtitles burned into the release print by laser (from 1988): clear white letters with a thin dark halo, then the print on a telecine. Use 'Cinema print, chemically etched' for older prints with ragged letters.",
    s: { standard: "PAL-I", transfer: { type: "telecine" }, overlay: { kind: "subtitle", style: "cinema_laser", text: "Where were you on the night of the storm?\nAt the lighthouse, as always." }, enabled: { channel: false }, view: { mode: "grab" } } },
  { id: "sub-vhs-release", group: "Subtitles", title: "Subtitled VHS release, 1990", evidence: "research",
    note: "A subtitled film on a rental VHS: Univers-style subtitles with a black edge on the master, softened by the tape. The edge treatment is [EST].",
    s: { standard: "PAL-I", transfer: { type: "telecine" }, overlay: { kind: "subtitle", style: "video_release", text: "Where were you on the night of the storm?\nAt the lighthouse, as always." }, recording: { format: "vhs_sp" }, enabled: { channel: false }, view: { mode: "grab" } } },
  { id: "sub-closed-captions", group: "Subtitles", title: "US closed captions, 1990", evidence: "research",
    note: "Line 21 captions drawn by the set's decoder: white capitals on black cells, 32 columns. The decoder's own font isn't documented, so VideoLook's dot font stands in.",
    s: { standard: "NTSC-M", camera: { type: "plumbicon3", overrides: { gamma: "bt709" } }, overlay: { kind: "subtitle", style: "cc608", text: "Where were you on the night of the storm?\nAt the lighthouse, as always." }, channel: { snrDb: 40 }, decoder: { ntscDemod: "equiband" }, set: { overscan: 0.05 }, view: { mode: "closeup" }, display: { tube: "slot", screenIn: 19, primaries: "SMPTEC", white: "K9300" } } },
];
const api = { LOOKS };
if (typeof module !== "undefined" && module.exports) module.exports = api;
